# Generated by Django 4.2 on 2024-02-26 05:53

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
